# Zweiter Server für 80

server {

    listen 80;
    listen [::]:80;
    server_name _; # Ihre IONOS-IP;

    # Pfad für die Certbot-Validierung
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Alles andere auf HTTPS umleiten
    location / {
        return 301 https://$host$request_uri;
    }
}

server {

    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _; # Ihre IONOS-IP
    
    # Neu für die SSL-Zertifikate
    ssl_certificate /etc/letsencrypt/live/livedata.sebastianscharnagl.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/livedata.sebastianscharnagl.com/privkey.pem;

    # Optimierungen
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

	# Weiterleiten, falls jemand an den Slash vergisst
    location = /dashboard-a {
      return 301 $scheme://$http_host/dashboard-a/;
    }

    location /dashboard-a/ {
        # '8080' so in dashboard.py festgelegt
        # Wichtig: Kein Slash am ende, damit nginx die URL als ganzes an python/dash weitergibt
        proxy_pass http://dashboard-a:8080; 
        
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Hilfreich für die Fehlersuche
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}