# Basis rate limiting für den Basis-Server
limit_req_zone $binary_remote_addr zone=base_limit:1m rate=1r/s;

# Rate limiting für die Dashboards
limit_req_zone $binary_remote_addr zone=dash_limit:1m rate=2r/s;

# Rate limiting für den Pusher
limit_req_zone $binary_remote_addr zone=pusher_limit:1m rate=1r/s;


# Umleitung, falls jemand auf 80 kommt

server {
    listen 80;
    listen [::]:80;
    server_name _; # Für Testing und Live-Betrieb unabhängig von der URL

    limit_req zone=base_limit burst=4 nodelay;

    
    # Pfad für die Certbot-Validierung
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Alles andere auf HTTPS umleiten
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _; # Ihre IONOS-IP

    limit_req zone=base_limit burst=4 nodelay;

    
    # Neu: Internen Docker-DNS verwenden
    resolver 127.0.0.11 valid=30s;
    
    # Neu für die SSL-Zertifikate
    ssl_certificate /etc/letsencrypt/live/livedata.sebastianscharnagl.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/livedata.sebastianscharnagl.com/privkey.pem;

    # Optimierungen
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

	# Weiterleiten, falls jemand an den Slash vergisst
    location = /dashboard-a {
      limit_req zone=dash_limit burst=5 nodelay;
      return 301 $scheme://$http_host/dashboard-a/;
    }

    location /dashboard-a/ {
        limit_req zone=dash_limit burst=20 nodelay;
      
        # '8080' so in dashboard.py festgelegt
        # Wichtig: Kein Slash am ende, damit nginx die URL als ganzes an python/dash weitergibt
        # Über diese Variable steuern wir, dass der DNS-Service von nginx verwendet wird
        # So kann auch nach einem Service-Neustart unter einer neuen internen IP der Service gefunden werden
        set $backend_dashboard_a "http://dashboard-a:8080";
        proxy_pass $backend_dashboard_a;
        
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Hilfreich für die Fehlersuche
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


	# Weiterleiten, falls jemand an den Slash vergisst
    location = /sensor-data-pusher {
      limit_req zone=pusher_limit burst=5 nodelay;
      return 301 $scheme://$http_host/sensor-data-pusher/;
    }

    location /sensor-data-pusher/ {
        limit_req zone=pusher_limit burst=10 nodelay;

        # Wichtig: Kein Slash am ende, damit nginx die URL als ganzes an python/dash weitergibt
        # Über diese Variable steuern wir, dass der DNS-Service von nginx verwendet wird
        # So kann auch nach einem Service-Neustart unter einer neuen internen IP der Service gefunden werden
        set $backend_sensor_data_pusher "http://sensor-data-pusher:5001";
        proxy_pass $backend_sensor_data_pusher;
        
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Hilfreich für die Fehlersuche
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


}