# Kleines Python-Linux holen
FROM python:3.11-slim

# Print-Ausgaben direkt ohne Puffer an Docker weitergeben
ENV PYTHONUNBUFFERED=1

# Arbeitsverzeichnis festlegen (best practice)
WORKDIR /app

# Systempakete installieren
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Python-Requirements installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Alles andere noch ins Docker-Image kopieren
COPY . .

# Port freigeben
EXPOSE 8080

# Healthcheck initiieren
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD curl -f http://localhost:8080/dashboard-a/ || exit 1

# Programm starten
CMD ["python", "dashboard_v2.py"]